### ISSUE TITLE
Improve UX Symmetry between Zombie Container Warning and Cleanup

### ISSUE THREAD

**Issue by davezuko** [binci/binci#78]
When starting a task, binci warns the user if there are any zombie containers that were not torn down correctly; it then suggests running `--cleanup` to remove them. The information given to the user, however, is different between the warning and cleanup: the warning displays the container name, but cleanup shows the container id. It would be awesome if we could make two small tweaks to make this more consistent:

1) Use the same identifier between the warning and cleanup task.
2) Make formatting consistent between the warning and cleanup task (one is comma-separated, the other is newline-separated).

Here's an example of what the users sees now:

![screen shot 2017-06-12 at 12 52 21 pm](https://user-images.githubusercontent.com/6439050/27047702-a0906b58-4f6e-11e7-90e7-5abe77322c5d.png)

**Comment by Fluidbyte** [comment]
The only challenge here would be that `docker ps -q` (which lists the containers) can only show the ID's. We could add a middle-step that would query all the ID's to get the names, but not sure about the overhead it would cause. Will investigate.

**Comment by Fluidbyte** [comment]
Ok, well immediately found my answer: `docker ps --format "{{.Names}}"`
