### ISSUE TITLE
Running multiple tasks for multiple containers

### ISSUE THREAD

**Issue by karneaud** [binci/binci#79]
Is the "tasks" related to the service container? or is it related to "binci" related services? I ask this because I have a service with where i need to run specific commands for php and node simultaneously. does the task initiate those commands for me?

**Comment by Fluidbyte** [comment]
The `tasks` define scripts that can be executed by the container, so if you have a task `foo` that just echo's "foo", then run `binci foo` it will be executed in the primary container.

If you need to run multiple commands you can do the following:

```yaml
tasks:
  foo: |
    echo "foo"
    echo "bar"
```

However, the above will fire in succession. If you need them run in parallel I would advise building a shell script which you can execute in the task.
