### ISSUE TITLE
Consider More Graceful Config Validation

### ISSUE THREAD

**Issue by davezuko** [binci/binci#80]
For example:

* Binci currently won't run if `env` is empty. What if I don't have any env vars to set?
* Binci currently won't run if `expose` is empty. What if I don't need to expose anything?

**Comment by Fluidbyte** [comment]
I'm not sure why you're having issues running without `env` or `expose`, the only config Binci requires is `from` and `tasks`, everything else is optional.

**Comment by Fluidbyte** [comment]
Oh, gotcha, missed the _empty_ and assumed _missing_. Will patch.
