### ISSUE TITLE
Mapping volumes from primary containers to service containers

### ISSUE THREAD

**Issue by karneaud** [binci/binci#81]
I'm trying to understand how to use binci but wanted to find out bout the volumes for the primary docker container and the service containers

to explain my dilemma...

I am trying to put together a wordpress development server where I need the following

1 Need a php server for wordpress
2 Need a mysql server
3 Want a nodejs server for theme development

For items 1 and 3 I want to be able to share " a particular volume" in the docker-compose way I'd simply reference the container and all volumes would be used. However I'm trying to see if I can share just a "specific" volume

In come binci If i created the 3 services would binci be able to distributor the specific volume to the 2 containers? How does the volumes for the primary server relate to the service container volumes?

**Comment by Fluidbyte** [comment]
Mapping volumes is the same for service containers as it is the primary, so, for example, if you wanted to map `/some/data` on your local to `/data` in the containers you could just do:

```yaml
from: node:6
services:
  - some-service:
      from: some-service
      volumes:
        - /some/data/:/data
volumes:
  - /some/data/:/data
tasks:
   ...
```

**Comment by karneaud** [comment]
well this is what's confusing here I take your scenario and given what I want to do...can't i

from: node:6
services:
  - php-service:
      from: php-service
      volumes:
       - primary-volume:/app:/data
    - node-service:
      from: node-service
      volumes:
       - /some/data:/src
volumes:
  - /some/data/:/app # primary volume
tasks: 

Why would I set volumes in the primary container?

**Comment by Fluidbyte** [comment]
I guess I'm confused by your use-case. I see what you're trying to do, but it seems to me it would make the most sense to create a single container that runs both Node and PHP, then just do what you need to in there.

Service containers are typically daemon/systemd type services like databases or cache systems, not actual code execution services; that's what you would do in your primary container.

**Comment by karneaud** [comment]
@Fluidbyte I'm beginning to see that my workflow might be wrong. I am trying to use a single container to run both node and php but I'm having trouble running multi services simultaneously and i'm not that fluent with linux command development. 

Orchestrating with docker-compose is becoming a real burden and kubernetes seemed too confusing. I thought binci might have been the answer but I was unable to get something up and running as it was not clear what the use case for binci and how to use binci

**Comment by karneaud** [comment]
I'm guessing what I can do is run node in the primary container and share the build to a persistent volume that can be used by both the php and node and access the php service via a node proxy.... thing is can binci accomplish this better than docker-compose?

**Comment by Fluidbyte** [comment]
You could use something like a [wordpress-node](https://hub.docker.com/r/hyettdotme/wordpress-node/) image for your primary container, then:

```yaml
from: hyettdotme/wordpress-node
services:
  - mysql:
      from: mysql
tasks:
   ...
```

The above (if I'm understanding the image, and your use-case correctly) would load wordpress with node in the container for your primary. Then any theme files you edit in the code would reflect in the running wordpress instance.

You can do this with Binci or Compose (or Kube if you really want all that overhead), but ultimately it's going to be about finding the right image to support WP and Node in the same primary container, a MySQL service, and exposing the correct environment variables so you can config the instance of WP.

**Comment by karneaud** [comment]
eventually that's what I'm doing

**Comment by karneaud** [comment]
I was looking for something like [this](https://www.howtoforge.com/tutorial/dockerizing-wordpress-with-nginx-and-php-fpm/) @Fluidbyte and was hoping I could have used binci instead of compose with binci "ssh"-ing into each service container and applying whatever config tasks

**Comment by Fluidbyte** [comment]
I see what you're looking for, my only advice would be to [avoid ssh-ing](https://jpetazzo.github.io/2014/06/23/docker-ssh-considered-evil/) to setup containers; it kind of misses the whole point.

You want to setup service containers that perform some task through automation, the same way every time. The power of docker is really the ephemeral nature and being able to build specific services that can be run exactly the same, every time.

My suggestion (generally) would be to create images. Use a Dockerfile to define what services are needed and (via `ENTRYPOINT`) how to start those up. Then those containers get linked to a primary container where you "work".

**Comment by karneaud** [comment]
this is what I was hoping to achieve using binci....I'm guessing this is note the case?

**Comment by Fluidbyte** [comment]
No, this is the case. What I'm saying is you need to build the services as containers first, implementing whatever scripting you need to run them.

**Comment by karneaud** [comment]
if it were possible to setup the primary container to handle the task of initialising see of the run time features needed for the services container without me having to go over and build my own Dockerfile

**Comment by Fluidbyte** [comment]
No, there isn't a way to do that.
