### ISSUE TITLE
Recommendation for replicating the host UID/GID in containers

### ISSUE THREAD

**Issue by lorefnon** [binci/binci#95]
What is the recommended way to ensure that host's UID and GID gets used in container without hardcoding the values in Dockerfile ? 

I am attempting to use [lein](https://leiningen.org) to scaffold a project with `binci -e` but generated files are owned by root by default and are not editable on host os where I run my editor. 

Unlike docker CLI, binci doesn't accept `--user` and I also don't see a way to pass build args. 

Given this is a development utility, would you consider having a simple way to ensure that host's UID/GID gets used in container ?

**Comment by Fluidbyte** [comment]
I think this could be resolved by allowing either some flag and/or config property that overrides the UID and GID. Typically this isn't a problem (as far as I've encountered) because _everything_ is done using Binci, so once owned by `1000`/`root` it really doesn't affect any future work with the files, but I can see how an exception could come into play.

**Comment by Fluidbyte** [comment]
I'm wondering if we could just expand on the [args in the command file](https://github.com/binci/binci/blob/master/src/command.js#L10) and use a config like `user: $UID`?

**Comment by lorefnon** [comment]
@Fluidbyte I didn't realize you were the primary maintainer of this project :smile:  Thanks for considering the suggestion.

I was exploring solutions in simiar space, and found that this was very easy to do in Vagrant, as the configuration allows arbitrary `create_args` to be [specified](https://www.vagrantup.com/docs/docker/configuration.html#create_args) for options that don't fit into Vagrant's generic configuration.

**Comment by Fluidbyte** [comment]
haha, yeah, recognized you right away! Long time!

I've kind of been wanting to do something similar, expose a bit more of the docker CLI to users so native args can be passed in more easily.

I'm really open to different approaches here, config or args both seem like reasonable approaches, I'd just prefer stay away from hard-coding `--user=$UID`.

Right now I (and @TomFrost, the other maintainer) are swamped; we keep coming back to ideas we've been wanting to implement on Binci for awhile, but just have no time. If you want to propose a PR I'm totally cool doing some back and forth. If not I'll see what I can work up as time allows.

**Comment by Fluidbyte** [comment]
One thought is just give Binci a `-u` arg [in the opts](https://github.com/binci/binci/blob/master/src/args.js#L26). Then it would just be a matter of modifying the [`command.getExec`](https://github.com/binci/binci/blob/master/src/command.js#L62) to add it to the command.
